server:
    #端口
    port: 8080
    session:
        #session过期期限
        timeout: 1000 # in seconds
    
spring:
    application:
        name: SYNCLOCK
    
    #db  -- 默认数据源
    #datasource:
    #mysql
        #url: jdbc:mysql://121.201.97.113:3306/coldchain_dev?characterEncoding=UTF-8&useSSL=false
        #username: root
        #password: Zqit3503
        #type: com.alibaba.druid.pool.DruidDataSource
        #driver-class-name: com.mysql.jdbc.Driver
    #oracle      
#        url: jdbc:oracle:thin:@129.158.105.196:1521:xe
#        username: ORECOIN
#        password: Bcaus2018
#        type: com.alibaba.druid.pool.DruidDataSource # 使用druid数据源
#        driver-class-name: oracle.jdbc.driver.OracleDriver
    #redis
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        pool:
            #使用负值表示没有限制
            max-active: 8
            #使用负值表示没有限制
            max-wait: -1
            max-idle: 8
            min-idle: 0
        #毫秒
        timeout: 10000
        
#mybatis                         
#mybatis:
    #mapper-locations: classpath:mapper/**/*Mapper.xml
    #configuration:
        #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
    
#日志管理            
logging: 
    level: 
        zqit: info
            
